doc:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "LICENSE"
          - "NOTICE"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
          - ".pre-commit-config.yaml"

test:
  - changed-files:
      - any-glob-to-any-file: "tests/**"

ui:
  - changed-files:
      - any-glob-to-any-file: "assets/**"

crate:models:
  - changed-files:
      - any-glob-to-any-file: "sovd-models/**"

crate:server:
  - changed-files:
      - any-glob-to-any-file: "sovd-server/**"

crate:diagnostic:
  - changed-files:
      - any-glob-to-any-file: "sovd-diagnostic/**"

crate:cli:
  - changed-files:
      - any-glob-to-any-file: "sovd-cli/**"
