doc:
  - "**/*.md"
  - "LICENSE"
  - "NOTICE"

ci:
  - ".github/**"
  - ".pre-commit-config.yaml"

test:
  - "tests/**"

ui:
  - "assets/**"

crate:opensovd-models:
  - "opensovd-models/**"

crate:opensovd-client:
  - "opensovd-client/**"

crate:opensovd-server:
  - "opensovd-server/**"

crate:opensovd-cli:
  - "opensovd-cli/**"

crate:opensovd-tracing:
  - "opensovd-tracing/**"

crate:opensovd-diagnostic:
  - "opensovd-diagnostic/**"


